### ISSUE TITLE
A dumb question

### ISSUE THREAD

**Issue by miguelgargallo** [ashwinhprasad/Chatbot-GoingMerry#1]
i = Input(shape=(input_shape,))

#creating the model

​

i = Input(shape=(input_shape,))

x = Embedding(vocabulary+1,10)(i)

x = LSTM(10,return_sequences=True)(x)

x = Flatten()(x)

x = Dense(output_length,activation="softmax")(x)

model  = Model(i,x)

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[14], line 3
      1 #creating the model
----> 3 i = Input(shape=(input_shape,))
      4 x = Embedding(vocabulary+1,10)(i)
      5 x = LSTM(10,return_sequences=True)(x)

NameError: name 'Input' is not defined

Do you know what happens me this error?

**Comment by ashwinhprasad** [comment]
[tensorflow keras input](https://www.tensorflow.org/api_docs/python/tf/keras/Input) is imported from tensorflow keras and is used to specify the input dimensions of the data that is fed to the network. it needs to be imported from tensorflow keras
